### ISSUE TITLE
GAN network and delta-features

### ISSUE THREAD

**Issue by felixwiberg** [rirnet/rirnet#60]
It seems like the delta-featured database is a good candidate for extended testing as it apparently performs best with current network structure. It is still hard to bring the validation error to a low level and therefore I feel we should investigate if there are improvements to be made if using GAN-structured networks. 

Below is an example from the validation dataset
![exampleoutpt](https://user-images.githubusercontent.com/17339037/46581744-0e35f380-ca3e-11e8-9d6a-2c366ccb5c90.png)

**Comment by majamarcela** [comment]
IT IS INSIDE
*doggowoof*
