### ISSUE TITLE
Try to use vector of amplitudes and positions instead of mfccs as target for the NN model

### ISSUE THREAD

**Issue by majamarcela** [rirnet/rirnet#63]
We realized that the raw IRFs in our training data consists of several delta functions with varying amplitude and positions in time. We want to try to use this as target for our networks.

**Comment by felixwiberg** [comment]
There are clear dependence within groups of reflections that use the same number of reflections between source and target but the dependence disappears in rooms with many different absorption coefficients.

**Comment by felixwiberg** [comment]
->67->master
