### ISSUE TITLE
Vary absorption

### ISSUE THREAD

**Issue by felixwiberg** [rirnet/rirnet#64]
See if the network can produce output reliably using a database generated with absorption coefficients that vary over each wall.

## Constant absorption 
![43880021_1874829685970326_6080545798364332032_n](https://user-images.githubusercontent.com/17339037/46863753-7e66bf80-ce18-11e8-9095-f95939a3ef1f.png)

## Varying absorption
![43664750_2153922161591694_3212966262774693888_n](https://user-images.githubusercontent.com/17339037/46863754-7eff5600-ce18-11e8-99fd-257177d70293.png)

**Comment by majamarcela** [comment]
seems hard

**Comment by felixwiberg** [comment]
seems easy

**Comment by felixwiberg** [comment]
implemented
