### ISSUE TITLE
Find a good transform for the target data (peaks)

### ISSUE THREAD

**Issue by felixwiberg** [rirnet/rirnet#67]
..such that it is interpretable by the network. Obviously the order of the data points in the target data is important af.

This transform might change when implementing solution to issue #64

**Comment by felixwiberg** [comment]
The decay over distance in the signals in the image-source-model were lowered substantially using 
```
alphas = room.sources[0].damping / np.log(np.log((4.*np.pi*distances)))
```
such that the reflection orders can be separated over the y-axis (amplitude). Then the peaks were sorted along the y-direction

## transformed
![transformed](https://user-images.githubusercontent.com/17339037/46915094-e6e3a700-cfa6-11e8-87ad-900cbff0c955.png)

## untransformed
![untransformed](https://user-images.githubusercontent.com/17339037/46915131-52c60f80-cfa7-11e8-88c3-7ccc297546e7.png)

**Comment by majamarcela** [comment]
found way extract reflection order from pyroomacoustics #woof
